### PR TITLE
Yarn only because it's the best, Markdown bold receive

### PR DESCRIPTION
**Pull request by RONTheCookie**

### CODE REVIEW

**Comment by ohlookitsderpy** [comment]
yes

**Comment by cloudrex** [comment]
Not everyone uses Yarn. Forcing yarn on users would force them to go through the Yarn installation process.

Either way, I feel that there is really no need for Yarn (NPM accomplishes the same goal).

Also, please consider using more appropriate commit names next time, thanks!

**Comment by ohlookitsderpy** [comment]
A better pull request would be to have ``npm install`` (or ``yarn``), giving users a choice and informing them that both work correctly. Or perhaps also a feature I've seen in projects where it uses yarn to install dependencies if it's found in the PATH.

**Comment by RONTheCookie** [comment]
I could also use [yarn-or-npm](https://www.npmjs.com/package/yarn-or-npm) but this PR is closed anyway.

**Comment by ohlookitsderpy** [comment]
that's a cool looking module

**Pull request closed without merging**
