### PR TITLE
Update discord.js to v12.3 (latest stable release)

### LINKED ISSUE #78: Pls update discordjs to 12, since 11 will die soon

### PR DESCRIPTION
**Pull request by chroventer**
Closes #78

### CODE REVIEW

**Comment by cloudrex** [comment]
@chroventer Does Discordjs v12 work with user tokens?

**Comment by chroventer** [comment]
@cloudrex, no, selfbots are discontinued in newer versions.

**Comment by cloudrex** [comment]
We want selfbot support tho

**Comment by chroventer** [comment]
In that case, you may revert this pull-request; but the sooner than later, the v11 will no longer work.

**Comment by cloudrex** [comment]
That is sadly true...

**Comment by chroventer** [comment]
@cloudrex Alternatively, we can create our own endpoints for Discord API to support the latest version of the API.

**Comment by cloudrex** [comment]
That's what I was thinking. I actually have had started a personal discord wrapper lib but I never had the time to continue it
https://github.com/cloudrex/ds
We could, in the future start or continue that library to support both user and bots.

As of right now, I'm sadly unable to maintain most of this project or new ones due to that I'm working on another large project currently and my schedule prevents that, but in the future once that's cleared up I'll actively update this and other projects I have on backlog.

**Comment by Rexogamer** [comment]
What happened to the package-lock?

**Comment by cloudrex** [comment]
@Rexogamer That's a good question.

**Comment by chroventer** [comment]
I will open a new PR with an updated package-lock file later.

**Pull request merged**
